### ISSUE TITLE
Setup data bank

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#11]
### Value Proposition

**to be able to** create a parent or child login, the app must have a data bank in the backend, where the newly created logins will be added and from where the necessary data will be fetched.

### Description

I will create a data bank with MongoDB and Mongoose which will be empty in the beginning, but it will have a pre-defined format, so that for every user an object can be added to the data bank, containing all the information of the user, like name, password, if the user is a child or a parent and their bank accounts.

### Acceptance Criteria

No acceptance criteria, since this is all backend.

### Tasks

- [x] create kidsFi DB in MongoDB
- [x] create a model for the DB
- [x] create connection to the DB

### Sizing/Complexity

**M**
