### ISSUE TITLE
Add functionality to the `Create parent account` button

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#13]
### Value Proposition

**As a** parent that wants to register a login **I need** to fill a form **to be able to** to create my parent login.

### Description

<img width="527" alt="Screenshot 2022-12-02 at 12 39 54" src="https://user-images.githubusercontent.com/49844133/205284962-0f180939-6ab1-4acf-aaf3-93ccdd47754c.png">

### Acceptance Criteria

- [x] after clicking the `register` radio button, a form to register a parent account appears, which includes a `create account` button; this button should then add a new user in the `users` DB on MongoDB.

### Tasks

- [x] pull from remote repo
- [x] create new branch
- [x] create a handleOnSubmit function, which inserts the data from the form (First Name, Last Name and Password) as a new user in the `users` DB from MongoDB.

### Sizing/Complexity

**M**
