### ISSUE TITLE
Implement sign in functionality for parent users

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#15]
Implement sign in functionality for parent users

### Value Proposition

**As a** registered user (both parent and child) **I need** to sign in into my account **to be able to** access the app's functions.

### Description

<img width="373" alt="Screenshot 2022-11-27 at 19 41 47" src="https://user-images.githubusercontent.com/49844133/205598359-20c5cad8-3400-4656-b306-ec9e06e24b3a.png">

### Acceptance Criteria

- [x] after choosing the sign in option in the main page or after submitting the register form, a sign in form will be visible
- [x] all 3 input fields (first name, last name and password) are required, otherwise the form will not be submitted
- [x] after typing all details in the form, the user presses the `Sign in` button and the values from the input fields will be compared to what exists in the database
- [x] should the login information not be correct, an error message will inform the user of which details are wrong
- [x] should the login information be correct, the dashboard (an empty page in this stage) will be visible

### Tasks

- [x] pull from remote repository
- [x] create new branch
- [x] add `required` property to all 3 inputs in the `sign in form`
- [x] add handleSubmit function for the `Sign in` button
  - [x] the function should fetch the data from MongoDB and store the info in a variable `data`
  - [x] compare the values from the `sign in form` with `data`
  - [x] should the information not match `data` then an error message must be displayed, informing the user which values are wrong
  - [x] should the information be correct, a new `section` called `Dashboard` will be displayed, which will contain only the text `under construction` in this stage
  - [x] add, commit and push the new branch into the remote repository

### Sizing/Complexity

**L**

**Comment by marcos-de-barros-vioque** [comment]
Well done, Mihai!
