### ISSUE TITLE
Add a savings account

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#16]
### Value Proposition

**As a** logged in parent user I need
**to be able to** add one or several savings accounts for my child

### Description

<img width="624" alt="Screenshot 2022-11-27 at 22 58 48" src="https://user-images.githubusercontent.com/49844133/205628449-4ff095c1-eeaf-4ea8-a754-79515ed2bc60.png">

### Acceptance Criteria

- [x] After pressing the add account icon in the previous step, a select menu will be visible, where the user can choose what type of account will be created
- [ ] in this stage, only the option savings account will be functional

### Tasks

- [ ] should the user select savings account, a new section will be visible, containing: 
    - [ ] an input for the start date
    - [ ] an input for the start amount
    - [ ] an input for the interest rate
    - [ ] an "add account" button (not functional yet)

### Sizing/Complexity

**S**
