### ISSUE TITLE
Add a stocks account

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#17]
### Value Proposition

**As a** logged in parent user I need
**to be able to** add a stocks account for my child

### Description

<img width="624" alt="Screenshot 2022-11-27 at 22 58 48" src="https://user-images.githubusercontent.com/49844133/205629102-af3dca24-8537-496e-954b-0cac601e803f.png">

### Acceptance Criteria

- [x] After pressing the add account icon in the previous step, a select menu will be visible, where the user can choose what type of account will be created
- [x] in this stage, only the option stocks account will be functional

### Tasks

- [x]  should the user select stocks account, a new section will be visible, containing:  
    - [x] an input for stock name
    - [x] an input for the WKN number
    - [x] an input for the buy date
    - [x] an input for the buy amount
    - [x] an input for the no. of stocks
    - [x] an "add account" button (not functional yet)

### Sizing/Complexity

**S**
