### ISSUE TITLE
Add a loan account

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#18]
### Value Proposition

**As a** logged in parent user I need
**to be able to** add one or several loan accounts for my child

### Description

<img width="624" alt="Screenshot 2022-11-27 at 22 58 48" src="https://user-images.githubusercontent.com/49844133/205629877-17c2e882-564e-408c-8e0f-cc60bfaec4a9.png">

### Acceptance Criteria

- [ ] After pressing the add account icon in the previous step, a select menu will be visible, where the user can choose what type of account will be created
- [ ] in this stage, only the option loan account will be functional

### Tasks

- [ ]  should the user select loan account, a new section will be visible, containing: 
    - [ ] an input for the start date
    - [ ] an input for the start amount
    - [ ] an input for the interest rate
    - [ ] an "add account" button (not functional in this stage)

### Sizing/Complexity

**S**
