### ISSUE TITLE
Implement functionality to the `Add account` button

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#19]
### Value Proposition

**As a** logged in parent **I need to be able to** add the bank account(s) I created in the previous steps.

### Description

<img width="624" alt="Screenshot 2022-11-27 at 22 58 48" src="https://user-images.githubusercontent.com/49844133/205630327-d09caa1b-5805-4613-9e39-d558d7541c6e.png">
<img width="679" alt="Screenshot 2022-11-27 at 20 26 43" src="https://user-images.githubusercontent.com/49844133/205630760-2d6d6456-2687-448c-9c47-ccd841d0c39e.png">
<img width="415" alt="Screenshot 2022-11-27 at 20 07 42" src="https://user-images.githubusercontent.com/49844133/205630830-5ecdf859-ce55-4832-99da-7123977d28f9.png">

### Acceptance Criteria

- [x] the newly created accounts will be visible in the parents dashboard, when they click the name of the child

### Tasks

- [x] create and implement a handleSubmit function to the `Add account` button
- [x] create and implement an onClick function for the button with the name of the child in the dashboard

### Sizing/Complexity

**M**

**Comment by actyvystom** [comment]
Obviously just a typo: As a logged in parent I need to be able to add the bank (account, I guess?)...

**Comment by mihaimazareanu** [comment]
@actyvystom Yes, a typo. 🙈 Corrected it now.
