### ISSUE TITLE
Setup start page

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#2]
### Value Proposition

As a visitor I need to see what options I have to log in.. For that there must be 2 options visible, one to register and one to login.

### Description
<img width="509" alt="Screenshot 2022-11-27 at 19 31 41" src="https://user-images.githubusercontent.com/49844133/204153213-715e5675-5ebb-4a65-a868-5e7c99abe904.png">
<img width="355" alt="Screenshot 2022-11-27 at 19 38 00" src="https://user-images.githubusercontent.com/49844133/204153487-daf1fd6e-7e70-48e1-8248-b64bae91eece.png">
<img width="373" alt="Screenshot 2022-11-27 at 19 41 47" src="https://user-images.githubusercontent.com/49844133/204153636-c47b0618-928e-4fba-ad2f-a64f82e7b87f.png">

### Acceptance Criteria

- [x] navbar displaying which page is active is visible
- [x] a short welcome message is visible
- [x] the user can see where to register and where to sign in
- [x] in case the user tries to register a child account, a message will show up prompting the user to login first, as children accounts can be created only by already existing parent accounts.
- [x] also, a sign in form will be visible, allowing the user to sign in (not functional yet)
- [x] if the user chooses to register a parent account, the sign in icon will change background and color and a sign up form will show up

### Tasks

- [x] create a new branch
- [x] add functionality to the navbar
- [x] create a short welcome message
- [x] create a section where the new user can choose to register a parent account, which will include:
    - [x] 2 radio buttons, for parent login and child login
    - [x] should the user select the parent login, a register form will be visible with the following fields:
        - [x] an input for first name
        - [x] an input for last name
        - [x] an input for the user to create a new password
        - [x] an input for the user to confirm the password
        - [x] a button to create parent login (not functional yet)
       - [x] no handleSubmit function yet, this will be part of a future user story
    - [x] should the user select a child account, a message will be visible informing the user that a child login can be created only if a parent login was already created.
    - [x] also the user will be prompted to either create a parent login or login if he already has a user login.
- [x] add, commit and push everything to the remote repository

### Sizing/Complexity

**M**
