### ISSUE TITLE
Setup accounts page

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#28]
### Value Proposition

**As a** logged in child **I need** to see which money accounts I have
**to be able to** get more details about them.

### Description

![Image](https://user-images.githubusercontent.com/49844133/208405908-65cb75bc-12a4-4191-8d22-74158a8dd5d2.png)

### Acceptance Criteria

- [x] if there are no money accounts yet, the child should be informed to ask his parents to add some
- [x] if there are any money accounts, then for each type there will be an animation present

### Tasks

- [x] check if `user` is defined
- [x] check if `user` is child
- [x] check if `user` has any money accounts
    - [x] if no accounts exist, then display a text informing the child to ask his parents to add some accounts
- [x] if accounts exist, then check what type of accounts there are and display an animation for each type
    

### Sizing/Complexity

**S**
