### ISSUE TITLE
Accounts page / piggy bank details

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#29]
### Value Proposition

**As a** logged in child **I need** to see the details of my piggy bank (if I have one)
**to be able to** add transactions (not active at this stage).

### Description

<img width="490" alt="Screenshot 2022-12-19 at 11 19 25" src="https://user-images.githubusercontent.com/49844133/208406375-36830117-98b9-461f-bf6d-b12506613a99.png">

### Acceptance Criteria

- [x] after clicking the piggy bank animation, a new section will be displayed, including the following details: 
    - [x] current amount (start amount at this stage, as transactions are not functional yet)
    - [x] a button for displaying more details (not active at this stage)
    - [x] a chart showing the initial amount and the current amount (dummy at this stage, will be implemented correctly in the next US)
    - [x] a form to give the child the possibility to add money to their piggy bank (not active at this stage)
    - [x] a form to give the child the possibility to subtract money from their piggy bank (not active at this stage)

### Tasks

- [x] create an `onClick` function for the piggy bank animation to display a new section
- [x] the new section must include a field showing the current amount in the piggy bank (startAmount in this stage, as transactions are not possible yet)
- [x] also a `Show Details` button (not active yet)
- [x] a dummy chart showing the current amount
- [x] a form containing an `input` with a `label` "Would you like to add something to your piggy bank?"
- [x] an `Add amount` button (not functional at this stage)
- [x] - [ ] a form containing an `input` with a `label` "Did you take money from the piggy bank?"
- [x] an `Subtract amount` button (not functional at this stage)

### Sizing/Complexity

**M**
