### ISSUE TITLE
Create dashboard for signed in parent users

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#3]
### Value Proposition

**As a** logged in parent user **I need** to be able to see which child users are linked to my login and also 
**to be able to** create new child users.

### Description
<img width="511" alt="Screenshot 2022-11-27 at 20 07 06" src="https://user-images.githubusercontent.com/49844133/204154825-e03fc484-a706-4075-89cd-8eca24266467.png">
<img width="415" alt="Screenshot 2022-11-27 at 20 07 42" src="https://user-images.githubusercontent.com/49844133/204154842-ee605fe9-b72e-4a07-9977-6f1db68f58b7.png">

### Acceptance Criteria

- [x] after successfully signed in, should the parent user not have any child logins linked to his account, a text `You didn't create any child accounts yet` should be visible
- [x] should there be any child accounts already linked to the parent user, a list with all the existing child logins linked to the parent login will be displayed
- [x] also a button to allow the parent user to add new child logins will be visible
- [x] after clicking one of the already existing child login, an empty list will be visible (this list will contain an overview with all the existing accounts (piggy bank, savings account etc)which will be implemented at a later stage)
- [x] and also a button that will allow the parent to add new accounts to the child login (not functional at this stage)

### Tasks

(for developers team)

- [x] pull everything from the remote main branch
- [x] create new branch
- [x] dynamically create a button for all the child users linked to the parent user
- [x] create an onClick function for all the child users which will display a list with already existing bank accounts (an empty list at this stage)
- [x] create a button to allow the parent user to add new bank accounts for that child user (not functional in this stage)

### Sizing/Complexity

**L**

**Comment by marcos-de-barros-vioque** [comment]
LGTM Mihai!
