### ISSUE TITLE
Add functionality to the `Show details` button

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#30]
### Value Proposition

**As a** logged in child **I need** to press the `Show details` button
**to be able to** see a chart representing my transactions.

### Description

<img width="403" alt="Screenshot 2022-12-19 at 11 51 05" src="https://user-images.githubusercontent.com/49844133/208409697-14a54d8d-64c4-4f02-b767-049501e8a407.png">
<img width="498" alt="Screenshot 2022-12-19 at 11 51 38" src="https://user-images.githubusercontent.com/49844133/208409716-ed8d1c43-e68a-4421-96a4-bbca195228f5.png">

### Acceptance Criteria

- [x] after pressing the `Show details` button, a list of all transactions will be displayed (a dummy list at this stage, as transactions are not functional yet)
- [x] the text of the button should change to `Hide details` 
- [x] the button should toggle the display of the new section

### Tasks

- [x] create an `onClick` function for the `Show details` button to toggle the display of the new section
- [x] create a new `section` which includes a list of all transactions (just a dummy list at this stage)
- [x] also a `select` menu to allow the user to filter the transactions (not active at this stage)

### Sizing/Complexity

**S**
