### ISSUE TITLE
Accounts page / savings account

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#31]
### Value Proposition

**As a** logged in child  **I need** to press the mouse animation
**to be able to** see the details of my savings account

### Description

<img width="713" alt="Screenshot 2022-12-19 at 12 14 43" src="https://user-images.githubusercontent.com/49844133/208413842-ad933414-2b7a-4a1f-a516-470ba7c5b79d.png">

### Acceptance Criteria

- [x] after clicking the mouse animation, a new section will be displayed, including the following details:
     - [x] current amount 
     - [x] start amount 
     - [x] a button for displaying more details (not active at this stage)
     - [ ]  a chart showing the development between the start and current date (dummy at this stage, will be implemented correctly in the next US)
 
### Tasks

- [x] create an onClick function for the mouse animation to display a new section
- [x]  the new section must include a field showing the current amount and the start amount
- [x] a chart showing the evolution of the account between start and current date (just a dummy chart at this stage)
- [x] also a Show Details button (not active yet)

### Sizing/Complexity

**S**
