### ISSUE TITLE
Add functionality to the `Show details` button (savings account)

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#32]
### Value Proposition

**As a** logged in child **I need** to press the `Show details` button
**to be able to** see the evolution of my savings account

### Description

<img width="401" alt="Screenshot 2022-12-19 at 12 04 39" src="https://user-images.githubusercontent.com/49844133/208414686-9450d165-931d-40e9-8599-e98435ac0a0e.png">
<img width="498" alt="Screenshot 2022-12-19 at 11 51 38" src="https://user-images.githubusercontent.com/49844133/208414776-83cfa12e-34de-4e43-99c4-f3ffe6fdb0f6.png">

### Acceptance Criteria

- [x] after pressing the `Show details` button, a new section will be visible, which will show:
    - [x] the start date
    - [x] a select menu to filter the transactions (not active at this stage)
    - [x] a chart displaying the evolution of the account according to the filter (just a dummy chart at this stage) 
- [x] the text of the button should change to `Hide details` 
- [x] the button should toggle the display of the new section

### Tasks

- [x] create an `onClick` function for the `Show details` button to toggle the display of the new section
- [x] create a new `section` which includes:
    - [x] the start date
    - [x] also a `select` menu to allow the user to filter the transactions (not active at this stage)
    - [x]  a chart displaying the evolution of the account according to the filter (just a dummy chart at this stage) 

### Sizing/Complexity

**S**
