### ISSUE TITLE
Accounts page / stocks account details

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#36]
### Value Proposition

**As a** logged in child **I need** to press on the stocks account animation 
**to be able to** to see the details of my stocks account (if I have one)

### Description

<img width="610" alt="Screenshot 2022-12-23 at 12 14 02" src="https://user-images.githubusercontent.com/49844133/209326579-db1f3050-a42b-4b99-91fe-cc7bf698a93d.png">

### Acceptance Criteria

- [x] after clicking the stocks account animation, a new section will be displayed, including the following details: 
    - [x] start amount 
    - [x] current value (start amount at this stage, as transactions are not functional yet)
    - [x] a button for displaying more details (not active at this stage)

### Tasks

- [x] create an `onClick` function for the stocks account animation to display a new section
- [x] the new section must include a field showing the current amount in the stocks account (startAmount in this stage, as transactions are not possible yet)
- [x] also the start amount
- [x] also a `Show Details` button (not active yet)

### Sizing/Complexity

**S**
