### ISSUE TITLE
Accounts page / loan account

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#37]
### Value Proposition

**As a** logged in child  **I need** to press the loan animation
**to be able to** see the details of my loan account

### Description

<img width="423" alt="Screenshot 2022-12-23 at 12 28 30" src="https://user-images.githubusercontent.com/49844133/209328593-c94049ae-2820-44ab-8fb1-c9dcc8e3a05e.png">

### Acceptance Criteria

- [x] after clicking the loan animation, a new section will be displayed, including the following details:
     - [x] current amount 
     - [x] start amount 
     - [x] a button for displaying more details (not active at this stage)
 
### Tasks

- [x] create an onClick function for the loan animation to display a new section
- [x]  the new section must include a field showing the current amount and the start amount
- [x] also a Show Details button (not active yet)

### Sizing/Complexity

**S**

**Comment by marvinRoellecke** [comment]
Hi Mihai,
nice user story!
One little thing, I wouldn't render the "show more details" button if it has not function. Better render it when you add the function to it.

**Comment by mihaimazareanu** [comment]
Marvin, our coaches told us to make smaller user stories, I have done almost all my app like this.
