### ISSUE TITLE
Add functionality to the `Show details` button / stocks account

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#38]
### Value Proposition

**As a** logged in child **I need** to press the `Show details` button
**to be able to** see a chart representing my transactions.

### Description

<img width="423" alt="Screenshot 2022-12-23 at 12 32 22" src="https://user-images.githubusercontent.com/49844133/209329084-71d3dbdc-15d9-48c4-a792-d8c856ae98b3.png">

### Acceptance Criteria

- [x] after pressing the `Show details` button, a new section will be displayed, containing:
    - [x] the name of the stock
    - [x] the start date
    - [x] a select menu (not functional yet)
    - [x] a graph animation (a dummy list at this stage, as transactions are not functional yet)
- [x] the text of the button should change to `Hide details` 
- [x] the button should toggle the display of the new section

### Tasks

- [x] create an `onClick` function for the `Show details` button to toggle the display of the new section
- [x] create a new `section` which includes:
    - [x] the name of the stock
    - [x] the start date
    - [x] a select menu (not functional yet)
    - [x] a graph animation (a dummy list at this stage, as transactions are not functional yet)

### Sizing/Complexity

**S**
