### ISSUE TITLE
Add functionality to the `Show details` button / loan account

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#39]
### Value Proposition

**As a** logged in child **I need** to press the `Show details` button
**to be able to** see the evolution of my loan account

### Description

<img width="422" alt="Screenshot 2022-12-23 at 12 38 22" src="https://user-images.githubusercontent.com/49844133/209330007-ed0f4bc1-5ebb-4f80-b6c6-0914219c08e6.png">

### Acceptance Criteria

- [x] after pressing the `Show details` button, a new section will be visible, which will show:
    - [x] the start date
    - [x] a select menu to filter the transactions (not active at this stage)
    - [x] a chart displaying the evolution of the account according to the filter (just a dummy chart at this stage) 
- [x] the text of the button should change to `Hide details` 
- [x] the button should toggle the display of the new section

### Tasks

- [x] create an `onClick` function for the `Show details` button to toggle the display of the new section
- [x] create a new `section` which includes:
    - [x] the start date
    - [x] also a `select` menu to allow the user to filter the transactions (not active at this stage)
    - [x]  a chart displaying the evolution of the account according to the filter (just a dummy chart at this stage) 

### Sizing/Complexity

**S**

**Comment by marvinRoellecke** [comment]
Nicely done!

Same comment as in the previous user story, render the select menu first when you write the logic for it.
