### ISSUE TITLE
Add new child users

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#4]
### Value Proposition

**As a** logged in parent user **I need**
**to be able to** to add new child users which will automatically be linked to my user.

### Description
<img width="679" alt="Screenshot 2022-11-27 at 20 26 43" src="https://user-images.githubusercontent.com/49844133/204155633-a2aa1b23-78f8-4cc2-b7f5-f9aed0041f4f.png">

![Image](https://user-images.githubusercontent.com/49844133/206437091-5bc2318f-d848-45cf-92f3-7f1d9ada2d54.png)

### Acceptance Criteria

- [x] On clicking the add child login button, a form will be visible which will allow the parent user to create the child login
- [x] after pressing the `create child login` button, a message will inform the parent user that the child login has been successfully created 

### Tasks

- [x] pull everything from the remote main branch
- [x] create a new branch
- [x] create an onClick function for the "add child login" button which will make a form with the following fields visible:
    - [x] an input field for first name
    - [x] an inout field for last name
    - [x] an input to choose a password
    - [x] an input to confirm the password
    - [x] a "create login" button
- [x] create a handleSubmit function to create a new child login
  - [x] the function should POST the information in MongoDB and change property `isChild` to `true` 
- [x] add, commit and push everything to the remote repository

### Sizing/Complexity

**M**

**Comment by actyvystom** [comment]
Hi Mihai, a very detailed one, I like it :)
Although I have a few comments:
- You mention a "create login" button in your task list, but there's none in your wireframe ("create account"?)... probably just a typo ;)
- I suggest to leave out the git flow tasks from the task list as they are obvious...
- One single acceptance criteria seems very little: what happens with the form that appears, required fields, how to create a child login, etc. or is it part of another user story?

**Comment by mihaimazareanu** [comment]
Hi Thomas,

I have written in the tasks that there will be a handleSubmit function for the form that will POST the info on MongoDB. Should I write another acceptance criteria for it as well?

**Comment by actyvystom** [comment]
> Hi Thomas,
> 
> I have written in the tasks that there will be a handleSubmit function for the form that will POST the info on MongoDB. Should I write another acceptance criteria for it as well?

Yes, please - the acceptance criteria is more from a user point of view as the task list is more focused on development tasks. So what happens if the user does not fill in any values, the child login already exists, etc. These would be all valid acceptance criteria.
