### ISSUE TITLE
Add functionality to the `Add amount` button in  piggy bank account

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#41]
### Value Proposition

**As a** logged in child user **I need** to press the `Add amount` button 
**to be able to** add money to my piggy bank

### Description

<img width="490" alt="Screenshot 2022-12-19 at 11 19 25" src="https://user-images.githubusercontent.com/49844133/209544258-4fe007c6-9ea1-481d-a7a2-fb9295148ff8.png">

### Acceptance Criteria

- [ ] after clicking the `Add amount` button the `current amount` should change to the corresponding value
- [ ] also, in the list of transactions, a new deposit should be visible, with the date of the transaction and the amount

### Tasks

- [ ] create a new api route `api/children/[childId]/accounts/[accountID]/transactions
- [ ] add the GET and POST methods for this route
- [ ] create an `addAmount()` function which should POST the amount in the `transactions` route
- [ ] the function should also GET the new transaction and insert it to the `user` state saved in `localStorage`
- [ ] create another function to add the amount of the transaction to the `current amount` variable.
- [ ] display the new `current amount` variable
- [ ] add the transaction in the list of transactions visible on the page

### Sizing/Complexity

**L**

**Comment by ufelgen** [comment]
Hi Mihai, good user story! In your design, the contrast of your "add" and "subtract" buttons is really low (text vs background) - no need to change the US, but I would style it differently in the actual implementation. and I'm wondering if you're using a database - you have the API but are storing the data in the local storage? sorry, I'm still confused by backend issues...
