### ISSUE TITLE
Add functionality to the `Subtract amount` button in  piggy bank account

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#42]
### Value Proposition

**As a** logged in child user **I need** to press the `Subtract amount` button 
**to be able to** subtract money from my piggy bank

### Description

<img width="490" alt="Screenshot 2022-12-19 at 11 19 25" src="https://user-images.githubusercontent.com/49844133/209544258-4fe007c6-9ea1-481d-a7a2-fb9295148ff8.png">

### Acceptance Criteria

- [ ] after clicking the `Subtract amount` button the `current amount` should change to the corresponding value
- [ ] also, in the list of transactions, a new withdrawal should be visible, with the date of the transaction and the amount

### Tasks

- [ ] create an `subtractAmount()` function which should POST the amount in the `transactions` route
- [ ] the function should also GET the new transaction and insert it to the `user` state saved in `localStorage`
- [ ] create another function to subtract the amount of the transaction to the `current amount` variable.
- [ ] display the new `current amount` variable
- [ ] add the transaction in the list of transactions visible on the page

### Sizing/Complexity

**L**

**Comment by ufelgen** [comment]
same as with the previous one :)
