### ISSUE TITLE
Add a piggy bank account

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#5]
### Value Proposition

**As a** logged in parent user **I need** 
**to be able to** add one or several bank accounts for my child

### Description

<img width="624" alt="Screenshot 2022-11-27 at 22 58 48" src="https://user-images.githubusercontent.com/49844133/204161873-d0c8a68b-bdd7-4dfc-85df-9a84c89420ca.png">

### Acceptance Criteria

- [x] After pressing the add account icon in the previous step, a select menu will be visible, where the user can choose what type of account will be created
- [x] in this stage, only the first option (piggy bank) will be functional

### Tasks

- [x] pull everything from the remote repository
- [x] create new branch
- [x] a select element with the following options:
    - [x] piggy bank
    - [x] savings account
    - [x] stocks account
    - [x] loan account
- [x] should the user select piggy bank, a new section will be visible, containing:
    - [x] an input for the current amount 
    - [x] an "add account" button (not functional yet)
- [x] add, commit and push everything to the remote repository
  

### Sizing/Complexity

**S**

**Comment by actyvystom** [comment]
Hi Mihai, 
basically also a nice one but too complex... 
I suggest breaking it down into one story per account.
