### ISSUE TITLE
Create Dashboard child user

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#6]
### Value Proposition

**As a** logged in child user **I need** **to be able to** see an overview of all my accounts.

### Description

![Image](https://user-images.githubusercontent.com/49844133/208377722-75ebeecf-3a03-4175-9524-fcdb59cd7e69.png)

### Acceptance Criteria

- [ ] after login, a welcome message will be visible and a piggy bank animation which will lead to the `accounts` page, where (at a later stage) the money accounts will be displayed.

### Tasks

- [ ] create a short welcome message and an animation
- [ ] Add a piggy bank animation in a `Link` component to activate the `accounts` page
- [ ] add another `arrows` animation pointing to the piggy bank link 
- [ ] add, commit and push everything to the remote repository

### Sizing/Complexity

**S**

**Comment by actyvystom** [comment]
Hi Mihai, 
a nice one! Just one little thing: as mentioned in previous user story, please leave out git workflow tasks from the task list ;)

**Comment by mihaimazareanu** [comment]
Done. 😄
