### ISSUE TITLE
Create navbar

### ISSUE THREAD

**Issue by mihaimazareanu** [mihaimazareanu/capstone-project-kidsfi#8]
### Value Proposition

**As a** a visitor 
**I want to be able to** see how I can navigate the website 

### Description

![Screenshot 2022-11-28 at 10 49 54](https://user-images.githubusercontent.com/49844133/204247033-c8afaa97-ab38-4d43-98ff-98abf5bafd95.png)

### Acceptance Criteria

- [x] logo is visible
- [x] navigation will be done through icons for the following menus:
    - [x] home (home icon)
    - [x] accounts (piggy bank icon)
    - [x] profile
- [x] the icons will not be functional yet

### Tasks

- [x] create a new branch
- [x] create a nav element which will include:
    - [x] logo
    - [x] home icon
    - [x] piggy bank icon
    - [x] profile icon

### Sizing/Complexity

**S**

**Comment by Nimbaland** [comment]
Well, done Mihai!
